config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here

  get 'spree-product-popup/dismissed/:id',  to: 'product_popups#dismissed_popup'
  post 'spree-product-popup/dismissed/:id', to: 'product_popups#dismissed_popup'

  post 'spree-product-popup/populate/', to: 'product_popups#populate'

  namespace :admin, path: Spree.admin_path do

    delete 'product_popups/:id/image', to: 'product_popups#remove_image', as: 'delete_product_popup_image'

    resources :product_popups
  end
end

app/models/spree/product_popup.rb
class Spree::ProductPopup < ActiveRecord::Base

  scope :active, -> {
    where('effective_date <= ? and expiration_date >= ?',Time.current.strftime("%Y-%m-%d"),Time.current.strftime("%Y-%m-%d"))
    .or(where('effective_date is null and expiration_date >= ?', Time.current.strftime("%y-%m-%d")))
    .or(where('expiration_date is null and effective_date <= ?', Time.current.strftime("%y-%m-%d")))
  }
  scope :past, -> { where('expiration_date < ?', Time.current.strftime("%Y-%m-%d")) }
  scope :future, -> { where('effective_date > ?', Time.current.strftime("%Y-%m-%d")) }

  # Model Fields:
  # url
  belongs_to :variant, class_name: 'Spree::Variant'
  has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::Image'
  accepts_nested_attributes_for :image
  delegate :name, to: :variant
  # effective_date
  # expiration_date
  # custom_copy
  # title
  # confirm_text
  # decline_text

  validates :variant, presence: true
  validates :match_url, presence: true
  validates_uniqueness_of :match_url
  validate :verify_date_range

  before_save :normalize_url

  def verify_date_range
    if (self.effective_date && self.expiration_date)
      errors.add(:base, 'The specified date range is invalid. Expiration date must be on or after the effective date') unless self.effective_date <= self.expiration_date
    end
  end

  def active?
    return can_display?() && (effective_date.nil? || effective_date <= Time.current.beginning_of_day) && (expiration_date.nil? || expiration_date >= Time.current.end_of_day)
  end

  def can_display?
    # Product Popups are designed to be a one-click add to cart experience.
    # If there is a reason the product can't be added to the cart--such as when
    # it's out of stock, or unavailable in a particular region-- then the popup
    # should not be displayed
    return (self.variant.price_in(Spree::Config[:currency]) && !self.variant.price.nil?) && (self.variant.can_supply?)
  end

  def normalize_url
    self.match_url.slice!(0) if self.match_url.starts_with?('/')
  end
end

app/controllers/spree/admin/product_popups_controller.rb
module Spree
  module Admin
    class ProductPopupsController < ResourceController

      def index
        @show_expired = params[:expired] || params[:expired] === "true" ? true : false
        @show_future = params[:future] || params[:future] === "true" ? true : false
        @show_active = params[:active] || params[:active] === "true" || !(@show_expired || @show_future) ? true : false

        if @show_expired
          @product_popups = Spree::ProductPopup.past.order("effective_date DESC")
        elsif @show_future
          @product_popups = Spree::ProductPopup.future.order("effective_date ASC")
        else
          @product_popups = Spree::ProductPopup.active.order("effective_date ASC")
        end
      end

      def update
        begin
          @product_popup.update_attributes(product_popup_params)
        rescue => e
          Rails.logger.error(error: e, error_message: e.message, error_trace: e.backtrace.join('\n'))
          flash[:error] = e.message
        end
        redirect_to edit_admin_product_popup_path(@product_popup)
      end

      def location_after_save
        edit_admin_product_popup_path(@product_popup)
      end

      def remove_image
        @product_popup = Spree::ProductPopup.find(params[:id])
        @product_popup.image.destroy
        @product_popup.save

        redirect_to edit_admin_product_popup_path(@product_popup)
      end

      def product_popup_params

        params[:product_popup].delete(:image_attributes) unless params[:product_popup][:image_attributes][:attachment]

        params.require(:product_popup).permit(
          [
            :variant_id,
            :effective_date,
            :expiration_date,
            :match_url,
            :headline,
            :confirm_text,
            :decline_text,
            :custom_copy,
            image_attributes: [
                :alt,
                :attachment
            ]
          ]
        )
      end

    end # END class
  end
end

app/controllers/spree/product_popups_controller.rb
module Spree
  class ProductPopupsController < Spree::StoreController

    def dismissed_popup
      if request.method == "GET"
        respond_to do |format|
          format.json { render json: session["dismissed_product_popup_#{params[:id]}"] ? true : false }
          # NOTE:   The popup ID is included in the session key to allow a different popup to appear on
          #         another page. If you want to display only one product popup at a time, you can override
          #         this behavior in your project.
        end
      else
        session["dismissed_product_popup_#{params[:id]}"] = true # TODO Fix this to match above. This is deliberate to facilitate testing
      end
    end

    def populate

      order    = current_order(create_order_if_necessary: true)
      variant  = Spree::Variant.find(params[:variant_id])
      quantity = params[:quantity].to_i
      options  = params[:options] || {}

      # 2,147,483,647 is crazy. See issue #2695.
      if quantity.between?(1, 2_147_483_647)
        begin
          order.contents.add(variant, quantity, options)
        rescue ActiveRecord::RecordInvalid => e
          error = e.record.errors.full_messages.join(", ")
        end
      else
        error = Spree.t(:please_enter_reasonable_quantity)
      end

      if error
        flash[:error] = error
      else
        session["dismissed_product_popup_#{params[:product_popup_id]}"] = true
        flash[:success] = "#{variant.product.name} has been added to your cart"
        #
        # respond_with(order) do |format|
        #   format.html { redirect_back_or_default(cart_path) }
        # end
      end

      redirect_back_or_default(spree.root_path)
    end

  end
end

app/helpers/spree/admin/product_popups_helper.rb
module Spree
  module Admin
    module ProductPopupsHelper

      # Display the popup's image on the backend editor. Default to the variant's
      # image if a custom image is not defined
      def product_popup_image(popup)

        if popup.image
          options = {
            style: 'max-width: 100%;'
          }
          options[:alt] = popup.image.alt ? popup.image.alt : popup.variant.name
          create_product_image_tag(popup.image, popup, options, 'large')
        else
          large_image(popup.variant)
        end

      end
    end
  end
end

app/views/spree/admin/product_popups/_form.html.erb
<div data-hook="admin_product_popup_form_fields">
  <%= f.field_container :product, class: ['form-group'], 'data-hook' => "product_id" do %>
    <%= f.label :product_id, Spree.t(:product) %>
    <%= f.collection_select :variant_id, Spree::Variant.active, :id, :name_and_sku, {include_blank: true}, {class: 'select2'} %>
    <%= f.error_message_on :variant_id %>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-sm-12">
      <%= f.field_container :effective_date, class: ["form-group"], 'data-hook' => "effective_date" do %>
        <%= f.label :effective_date, Spree.t(:effective_date) %>
        <%= f.text_field :effective_date, value: datepicker_field_value(@product_popup.effective_date), class: 'datepicker datepicker-from form-control', autocomplete: :off %>
        <%= f.error_message_on :effective_date %>
      <% end %>
    </div>

    <div class="col-md-6 col-sm-12">
      <%= f.field_container :expiration_date, class: ["form-group"], 'data-hook' => "expiration_date" do %>
        <%= f.label :expiration_date, Spree.t(:expiration_date) %>
        <%= f.text_field :expiration_date, value: datepicker_field_value(@product_popup.expiration_date), class: 'datepicker datepicker-to form-control', autocomplete: :off %>
        <%= f.error_message_on :expiration_date %>
      <% end %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr><td colspan="2">
        <%= f.label :match_url, Spree.t(:popup_url) %>
      </td></tr>
    </thead>

    <tbody>
      <tr>
        <td>
          <%= current_store.url %>/
        </td>
        <td width="100%">
          <%= f.field_container :match_url, class: ['form-group'], 'data-hook' => "match_url" do %>
            <%= f.text_field :match_url, value: @product_popup.match_url, class: 'form-control', autocomplete: 'off' %>
            <%= f.error_message_on :match_url %>
          <% end %>
        </td>
      </tr>
      <tr class="small">
        <td colspan="2">
          Enter a path relative to the site's domain (e.g. <code>products/my-product</code> or <code>categories/featured-items</code>)
        </td>
      </tr>
    </tbody>
  </table>


  <div data-hook="additional_product_popup_fields"></div>
</div>

app/views/spree/admin/product_popups/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:product_popups), spree.admin_product_popups_url %> /
  <%= @product_popup.variant.name.capitalize %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product_popup } %>
<div class="panel panel-default">
  <div class="panel-heading">Edit this Popup</div>

  <div class="panel-body">
    <%= form_for [:admin, @product_popup] do |f| %>
      <fieldset>
        <%= render partial: 'form', locals: { f: f } %>

        <%= f.field_container :headline, class: ["form-group"], 'data-hook' => "headline" do %>
          <%= f.label :headline, Spree.t(:headline) %>
          <div class="small">If this is left blank, the product's name will be used instead</div>
          <%= f.text_field :headline, value: @product_popup.headline, class: 'form-control' %>
          <%= f.error_message_on :headline %>
        <% end %>

        <%= f.fields_for :image_attributes do |image_fields| %>
          <% image = @product_popup.image %>
          <div data-hook="admin_image_form_fields" class="row">
            <div class="col-xs-12"><h3>Custom Image</h3></div>
            <div class="col-xs-6 col-md-6 col-xs-offset-3 col-md-offset-0">

              <% if image.blank? %>
                <p>
                  No custom image selected. The product image will be used instead.
                </p>
              <% else %>
                <div class="image-wrapper">
                  <%= product_popup_image(@product_popup) %>
                </div>

                <%= link_to('Remove Image', admin_delete_product_popup_image_path(@product_popup), class: 'btn btn-primary', method: :delete) %>
              <% end %>
            </div>

            <div class="col-xs-12 col-md-6">
              <div data-hook="alt_text" class="form-group">
                <div data-hook="file" class="form-group">
                  <%= image_fields.label :attachment, Spree.t(:filename) %>
                  <%= image_fields.file_field :attachment %>
                </div>
                <div class="form-group">
                  <%= image_fields.label :alt, Spree.t(:alt_text) %>
                  <div class="small">Defaults to the variant name</div>
                  <%= image_fields.text_area :alt, rows: 4, class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="row">
          <div class="col-xs-12 col-md-6">
            <%= f.field_container :confirm_text, class: ["form-group"], 'data-hook' => "confirm_text" do %>
              <%= f.label :confirm_text, Spree.t(:confirm_text) %>
              <div class="small">Defaults to 'Add to Cart'</div>
              <%= f.text_field :confirm_text, value: @product_popup.confirm_text, class: 'form-control', maxlength: 15 %>
              <%= f.error_message_on :confirm_text %>
            <% end %>
          </div>

          <div class="col-xs-12 col-md-6">
            <%= f.field_container :decline_text, class: ["form-group"], 'data-hook' => "decline_text" do %>
              <%= f.label :decline_text, Spree.t(:decline_text) %>
              <div class="small">Defaults to 'No Thanks'</div>
              <%= f.text_field :decline_text, value: @product_popup.decline_text, class: 'form-control', maxlength: 15 %>
              <%= f.error_message_on :decline_text %>
            <% end %>
          </div>
        </div>

        <%= f.field_container :custom_copy, class: ["form-group"], 'data-hook' => "custom_copy" do %>
          <%= f.label :custom_copy, Spree.t(:custom_copy) %>
          <div class="small">Enter custom text and/or HTML content. If this is left blank, the product's description will be used instead</div>
          <%= f.text_area :custom_copy, value: @product_popup.custom_copy, rows: 20, class: 'form-control' %>
          <%= f.error_message_on :custom_copy %>
        <% end %>

        <%= render partial: 'spree/admin/shared/edit_resource_links' %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/spree/admin/product_popups/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:product_popup) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_product_popup), new_admin_product_popup_url, class: "btn-success", icon: 'add', id: 'admin_new_product_popup' %>
<% end if can? :create, Spree::ProductPopup %>

<%= #render 'spree/admin/shared/index_table_options', collection: @product_popups
%>

<ul class="nav nav-tabs">
  <li role="presentation" class="<%= @show_active ? 'active' : '' %>">
    <%= link_to "Active", admin_product_popups_path(active: true) %>
  </li>
  <li role="presentation" class="<%= @show_expired ? 'active' : '' %>">
    <%= link_to "Expired", admin_product_popups_path(expired: true) %>
  </li>
  <li role="presentation" class="<%= @show_future ? 'active' : '' %>">
    <%= link_to "Future", admin_product_popups_path(future: true) %>
  </li>
</ul>

<% if @product_popups.any? %>
  <% @product_popups = @product_popups.page(params[:page]).per(params[:per_page] || 15) %>
  <%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @product_popups } %>

  <table class="table" id="listing_events" data-hook>
    <thead>
      <tr data-hook="admin_events_index_headers">
        <th>Variant</th>
        <th>Effective Date</th>
        <th>Expiration Date</th>
        <th data-hook="admin_events_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @product_popups.each do |popup| %>
      <tr data-hook="admin_events_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= link_to popup.variant.product.name, edit_admin_product_popup_path(popup) %></td>
        <td><%= popup.effective_date %></td>
        <td><%= popup.expiration_date %></td>
        <td class='actions actions-1' data-hook="admin_events_index_row_actions">
          <%= link_to_edit_url edit_admin_product_popup_path(popup), title: "admin_edit_#{dom_id(popup)}", no_text: true %>
          <%= link_to_delete popup, title: "admin_delete_#{dom_id(popup)}", no_text: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ProductPopup)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_product_popup_url) if can? :create, Spree::ProductPopup %>!
  </div>
<% end %>

app/views/spree/admin/product_popups/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:product_popup), spree.admin_product_popups_url %> /
  <%= Spree.t(:new_product_popup) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product_popup } %>

<%= form_for [:admin, @product_popup] do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>