config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here

  get 'spree-product-popup/dismissed/:id',  to: 'product_popups#dismissed_popup'
  post 'spree-product-popup/dismissed/:id', to: 'product_popups#dismissed_popup'

  post 'spree-product-popup/populate/', to: 'product_popups#populate'

  namespace :admin, path: Spree.admin_path do

    delete 'product_popups/:id/image', to: 'product_popups#remove_image', as: 'delete_product_popup_image'

    resources :product_popups
  end
end

app/models/spree/product_popup.rb
class Spree::ProductPopup < ActiveRecord::Base

  scope :active, -> {
    where('effective_date <= ? and expiration_date >= ?',Time.current.strftime("%Y-%m-%d"),Time.current.strftime("%Y-%m-%d"))
    .or(where('effective_date is null and expiration_date >= ?', Time.current.strftime("%y-%m-%d")))
    .or(where('expiration_date is null and effective_date <= ?', Time.current.strftime("%y-%m-%d")))
  }
  scope :past, -> { where('expiration_date < ?', Time.current.strftime("%Y-%m-%d")) }
  scope :future, -> { where('effective_date > ?', Time.current.strftime("%Y-%m-%d")) }

  # Model Fields:
  # url
  belongs_to :variant, class_name: 'Spree::Variant'
  has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::Image'
  accepts_nested_attributes_for :image
  delegate :name, to: :variant
  # effective_date
  # expiration_date
  # custom_copy
  # title
  # confirm_text
  # decline_text

  validates :variant, presence: true
  validates :match_url, presence: true
  validates_uniqueness_of :match_url
  validate :verify_date_range

  before_save :normalize_url

  def verify_date_range
    if (self.effective_date && self.expiration_date)
      errors.add(:base, 'The specified date range is invalid. Expiration date must be on or after the effective date') unless self.effective_date <= self.expiration_date
    end
  end

  def active?
    return can_display?() && (effective_date.nil? || effective_date <= Time.current.beginning_of_day) && (expiration_date.nil? || expiration_date >= Time.current.end_of_day)
  end

  def can_display?
    # Product Popups are designed to be a one-click add to cart experience.
    # If there is a reason the product can't be added to the cart--such as when
    # it's out of stock, or unavailable in a particular region-- then the popup
    # should not be displayed
    return (self.variant.price_in(Spree::Config[:currency]) && !self.variant.price.nil?) && (self.variant.can_supply?)
  end

  def normalize_url
    self.match_url.slice!(0) if self.match_url.starts_with?('/')
  end
end

app/controllers/spree/admin/product_popups_controller.rb
module Spree
  module Admin
    class ProductPopupsController < ResourceController

      def index
        @show_expired = params[:expired] || params[:expired] === "true" ? true : false
        @show_future = params[:future] || params[:future] === "true" ? true : false
        @show_active = params[:active] || params[:active] === "true" || !(@show_expired || @show_future) ? true : false

        if @show_expired
          @product_popups = Spree::ProductPopup.past.order("effective_date DESC")
        elsif @show_future
          @product_popups = Spree::ProductPopup.future.order("effective_date ASC")
        else
          @product_popups = Spree::ProductPopup.active.order("effective_date ASC")
        end
      end

      def update
        begin
          @product_popup.update_attributes(product_popup_params)
        rescue => e
          Rails.logger.error(error: e, error_message: e.message, error_trace: e.backtrace.join('\n'))
          flash[:error] = e.message
        end
        redirect_to edit_admin_product_popup_path(@product_popup)
      end

      def location_after_save
        edit_admin_product_popup_path(@product_popup)
      end

      def remove_image
        @product_popup = Spree::ProductPopup.find(params[:id])
        @product_popup.image.destroy
        @product_popup.save

        redirect_to edit_admin_product_popup_path(@product_popup)
      end

      def product_popup_params

        params[:product_popup].delete(:image_attributes) unless params[:product_popup][:image_attributes][:attachment]

        params.require(:product_popup).permit(
          [
            :variant_id,
            :effective_date,
            :expiration_date,
            :match_url,
            :headline,
            :confirm_text,
            :decline_text,
            :custom_copy,
            image_attributes: [
                :alt,
                :attachment
            ]
          ]
        )
      end

    end # END class
  end
end

app/controllers/spree/product_popups_controller.rb
module Spree
  class ProductPopupsController < Spree::StoreController

    def dismissed_popup
      if request.method == "GET"
        respond_to do |format|
          format.json { render json: session["dismissed_product_popup_#{params[:id]}"] ? true : false }
          # NOTE:   The popup ID is included in the session key to allow a different popup to appear on
          #         another page. If you want to display only one product popup at a time, you can override
          #         this behavior in your project.
        end
      else
        session["dismissed_product_popup_#{params[:id]}"] = true # TODO Fix this to match above. This is deliberate to facilitate testing
      end
    end

    def populate

      order    = current_order(create_order_if_necessary: true)
      variant  = Spree::Variant.find(params[:variant_id])
      quantity = params[:quantity].to_i
      options  = params[:options] || {}

      # 2,147,483,647 is crazy. See issue #2695.
      if quantity.between?(1, 2_147_483_647)
        begin
          order.contents.add(variant, quantity, options)
        rescue ActiveRecord::RecordInvalid => e
          error = e.record.errors.full_messages.join(", ")
        end
      else
        error = Spree.t(:please_enter_reasonable_quantity)
      end

      if error
        flash[:error] = error
      else
        session["dismissed_product_popup_#{params[:product_popup_id]}"] = true
        flash[:success] = "#{variant.product.name} has been added to your cart"
        #
        # respond_with(order) do |format|
        #   format.html { redirect_back_or_default(cart_path) }
        # end
      end

      redirect_back_or_default(spree.root_path)
    end

  end
end

app/helpers/spree/admin/product_popups_helper.rb
module Spree
  module Admin
    module ProductPopupsHelper

      # Display the popup's image on the backend editor. Default to the variant's
      # image if a custom image is not defined
      def product_popup_image(popup)

        if popup.image
          options = {
            style: 'max-width: 100%;'
          }
          options[:alt] = popup.image.alt ? popup.image.alt : popup.variant.name
          create_product_image_tag(popup.image, popup, options, 'large')
        else
          large_image(popup.variant)
        end

      end
    end
  end
end

app/views/spree/frontend/product_popups/_product_popup.html.erb
<%
  # NOTE: The product show template has conditionals that control whether a product can be added
  #       to a cart. These same checks fire before returning @product_popup. If the user can't
  #       purchase the item for any reason, there's no reason to taunt them with it.
  #
  #       If a matching popup for the current URL cannot be displayed due to the reasons outlined
  #       above, the gem will try to locate a more generic popup on the same path hierarchy.
  #
  #             For example, if Product A is set to popup on `products/alpha`, and Product B is
  #             set to popup on `products`, if Product A is out of stock, the Product B popup
  #             will be displayed instead.
%>

<% if !(@product_popup.nil?) %>
  <% variant = @product_popup.variant %>
  <div class='modal spree-product-popup-modal' id='modal-product-popup' tabindex='-1' role='dialog' aria-labelledby='product-popup' aria-hidden='true'>
    <div class='modal-dialog' role='document'>
      <div class='modal-content'>

        <div class='modal-header product-popup-header'>
          <button class='btn btn-primary close' type='button' data-dismiss='modal' aria-label='Close'>
            <i class='icon-closeMobile'></i>
          </button>
        </div>

        <div class="modal-body product-popup-body">
          <div class="col-xs-10 col-lg-8 col-xs-offset-1 col-lg-offset-2 bg-light">
            <div class="row text-center product-popup-title-wrapper">
              <div class="col-xs-10 col-xs-offset-1">
                <h1 class="product-popup-title"><%= @product_popup.headline.blank? ? variant.name : @product_popup.headline %></h1>
              </div>
            </div>

            <div class="row product-popup-image-wrapper">
              <div class="col-xs-8 col-lg-6 col-xs-offset-2 col-lg-offset-3">
                <p class="text-center"><%= product_popup_image(@product_popup) %></p>
              </div>
            </div>

            <div class="row text-center product-popup-copy-wrapper">
              <div class="col-xs-10 col-xs-offset-1 product-popup-copy">
                <% if (@product_popup.custom_copy.blank?) %>
                  <%= raw(variant.description) rescue spree.t(:product_has_no_description)  %>
                <% else %>
                  <%= raw(@product_popup.custom_copy) %>
                <% end %>
              </div>
            </div>

            <div class="row text-center product-popup-toolbar-wrapper">
              <div class="col-xs-8 col-md-6 col-xs-offset-2 col-md-offset-3">
                <div class="row product-popup-toolbar">
                  <div class="col-xs-12 col-sm-6">
                    <%= form_for :order, url: spree_product_popup_populate_path do |f| %>
                      <%= hidden_field_tag :quantity, 1 %>
                      <%= hidden_field_tag :product_popup_id, @product_popup.id %>
                      <%= hidden_field_tag "variant_id", variant.id %>
                      <%= button_tag class: 'btn btn-success product-popup-btn product-popup-add', id: 'popup-add-to-cart-button', type: :submit, 'aria-label' => 'Add to cart' do %>
                        <%= @product_popup.confirm_text.blank? ? Spree.t(:product_popup_add_cart) : @product_popup.confirm_text %>
                      <% end %>
                    <% end %>
                  </div>

                  <div class="col-xs-12 col-sm-6">
                    <button class='btn btn-success product-popup-btn product-popup-close' type='button' data-dismiss='modal' aria-label='Close'>
                      <%= @product_popup.decline_text.blank? ? Spree.t(:product_popup_no_thanks) : @product_popup.decline_text %>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    $.ajax({
      url: '/spree-product-popup/dismissed/<%= @product_popup.id %>',
      type: 'GET',
      dataType: "json",
      success: function(data) {
        if (!data) {
          setTimeout(displayPopup, 10000);
          function displayPopup() {
            $('#modal-product-popup').modal('show');
          }
        }
      }
    })

    $('#modal-product-popup').on('hidden.bs.modal', function () {
      $.ajax({
        url: '/spree-product-popup/dismissed/<%= @product_popup.id %>',
        type: 'POST',
        data: true
      })
    })
  </script>
<% end %>